name: school_taxi
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  table_calendar: ^3.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3  # ローカル用
  cloud_firestore: ^4.8.3     # Firebase用
  firebase_core: ^2.30.0
  numberpicker: ^2.1.2
  url_launcher: ^6.1.14 # または最新バージョン
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0


flutter_icons:
  android: true
  ios: true
  image_path: images/icon.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf



